2014-11-17 13:09:24,293 - [INFO] - from play in pool-14-thread-5 
Listening for HTTP on /0:0:0:0:0:0:0:0:9000

2014-11-17 13:09:40,920 - [INFO] - from play in play-internal-execution-context-1 
database [default] connected at jdbc:h2:mem:play

2014-11-17 13:09:44,366 - [ERROR] - from application in New I/O worker #1 


! @6k8d3ooad - Internal server error, for (GET) [/client/delete/Apple%20CTO%20MacBook%20Air%201.4%20GHz%2011%22,%20256%20GB,%208%20GB%20RAM] ->

play.api.db.evolutions.InvalidDatabaseRevision: Database 'default' needs evolution![An SQL script need to be run on your database.]
	at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1$$anonfun$apply$1.apply$mcV$sp(Evolutions.scala:510) ~[na:na]
	at play.api.db.evolutions.EvolutionsPlugin.withLock(Evolutions.scala:531) ~[na:na]
	at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1.apply(Evolutions.scala:485) ~[na:na]
	at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1.apply(Evolutions.scala:483) ~[na:na]
	at scala.collection.immutable.List.foreach(List.scala:318) ~[na:na]
	at play.api.db.evolutions.EvolutionsPlugin.onStart(Evolutions.scala:483) ~[na:na]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91) ~[na:na]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91) ~[na:na]
	at scala.collection.immutable.List.foreach(List.scala:318) ~[na:na]
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91) ~[na:na]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91) ~[na:na]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91) ~[na:na]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[na:na]
	at play.api.Play$.start(Play.scala:90) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:157) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:130) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:130) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:128) ~[na:na]
	at scala.util.Success.flatMap(Try.scala:200) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:128) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[na:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[na:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[na:na]
	at com.typesafe.trace.FutureRunnable.run(FutureTrace.scala:119) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[na:na]

2014-11-17 13:09:51,729 - [INFO] - from play in play-internal-execution-context-1 
database [default] connected at jdbc:h2:mem:play

2014-11-17 13:09:51,937 - [INFO] - from application in play-internal-execution-context-1 
Scheduler started

2014-11-17 13:09:52,103 - [INFO] - from play in play-internal-execution-context-1 
Starting application default Akka system.

2014-11-17 13:09:52,132 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2014-11-17 13:09:53,361 - [INFO] - from application in slick.db.execution.context-1 
delete client: Apple CTO MacBook Air 1.4 GHz 11", 256 GB, 8 GB RAM

2014-11-17 13:10:05,691 - [ERROR] - from application in play-akka.actor.default-dispatcher-7 


! @6k8d40405 - Internal server error, for (GET) [/register] ->

play.api.Application$$anon$1: Execution exception[[OAuthNotAuthorizedException: Authorization failed (server replied with a 401). This can happen if the consumer key was not correct or the signatures did not match.]]
	at play.api.Application$class.handleError(Application.scala:296) ~[na:na]
	at play.api.DefaultApplication.handleError(Application.scala:402) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:205) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:202) [na:na]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33) [na:na]
	at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:185) [na:na]
	at scala.util.Try$.apply(Try.scala:161) [na:na]
	at scala.util.Failure.recover(Try.scala:185) [na:na]
	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) [na:na]
	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at play.api.libs.iteratee.Execution$trampoline$.execute_aroundBody0(Execution.scala:46) [na:na]
	at play.api.libs.iteratee.Execution$trampoline$.execute_aroundBody1$advice(Execution.scala:138) [na:na]
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:1) [na:na]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete_aroundBody2(Promise.scala:248) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise$AjcClosure3.run(Promise.scala:1) [na:na]
	at com.typesafe.trace.FutureTraceAspect.ajc$around$com_typesafe_trace_FutureTraceAspect$4$3fd2d6f0proceed(FutureTraceAspect.aj:148) [na:na]
	at com.typesafe.trace.FutureTraceAspect.ajc$around$com_typesafe_trace_FutureTraceAspect$4$3fd2d6f0(FutureTraceAspect.aj:150) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:244) [na:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [na:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23) [na:na]
	at com.typesafe.trace.FutureRunnable.run(FutureTrace.scala:119) [na:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41) [na:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393) [na:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [na:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [na:na]
Caused by: oauth.signpost.exception.OAuthNotAuthorizedException: Authorization failed (server replied with a 401). This can happen if the consumer key was not correct or the signatures did not match.
	at oauth.signpost.AbstractOAuthProvider.handleUnexpectedResponse(AbstractOAuthProvider.java:243) ~[na:na]
	at oauth.signpost.AbstractOAuthProvider.retrieveToken(AbstractOAuthProvider.java:193) ~[na:na]
	at oauth.signpost.AbstractOAuthProvider.retrieveRequestToken(AbstractOAuthProvider.java:74) ~[na:na]
	at play.api.libs.oauth.OAuth.retrieveRequestToken(OAuth.scala:38) ~[na:na]
	at controllers.Twitter$$anonfun$register$1$$anonfun$apply$2.apply(Twitter.scala:31) ~[classes/:na]
	at controllers.Twitter$$anonfun$register$1$$anonfun$apply$2.apply(Twitter.scala:31) ~[classes/:na]
	at scala.Option.getOrElse(Option.scala:120) ~[na:na]
	at controllers.Twitter$$anonfun$register$1.apply(Twitter.scala:30) ~[classes/:na]
	at controllers.Twitter$$anonfun$register$1.apply(Twitter.scala:19) ~[classes/:na]
	at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:433) ~[na:na]
	at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:432) ~[na:na]
	at play.api.mvc.Action$.invokeBlock(Action.scala:556) ~[na:na]
	at play.api.mvc.Action$.invokeBlock(Action.scala:555) ~[na:na]
	at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:518) ~[na:na]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) ~[na:na]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) ~[na:na]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[na:na]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:129) ~[na:na]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:128) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[na:na]
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:128) ~[na:na]
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:121) ~[na:na]
	at play.api.libs.iteratee.DoneIteratee$$anonfun$mapM$2.apply(Iteratee.scala:705) ~[na:na]
	at play.api.libs.iteratee.DoneIteratee$$anonfun$mapM$2.apply(Iteratee.scala:705) ~[na:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [na:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [na:na]
	... 7 common frames omitted

